### ISSUE TITLE
Haven't defined lf_ch_out

### ISSUE THREAD

**Issue by aaryapatel007** [l5shi/Octave-Conv-Keras#1]
https://github.com/l5shi/Octave-Conv-Keras/blob/b3c727453081b697a8579cc6a95f46051f85a6a7/last_octconv.py#L17
It should be hf_ch_out. I think u should do `UpSampling2D `of the lf_conv and then add the hf_conv and upsampled data to get the final output. See figure 2(a) of the paper when alpha_out = 0 only two paths are left in which one is Upsample2D.

**Comment by l5shi** [comment]
Thanks for your notification. I have fixed the typo right now.
